# Special Matrices

In [1]:
import numpy as np

#### Creating Matrices from given elements

A matrix can be created from array-like objects using the `numpy.array()` function.

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
A = np.arange(1, 10).reshape(3 , 3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Special Matrices

#### Idenitity Matrix

A square matrix that has diagonal values 1 and 0 everywhere else.

For example, a 3x3 identity matrix.

$$I_3 = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}$$

A matrix can be created by specifying the number of rows/columns using the `numpy.array()` function.

In [6]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Properties**


Multiplicative Identity:

For any matrix $A$ of the same size as $I_{n}$, the product is $A$ itself:

$$A \times I_{n} = I_{n} \times A = A$$

In [17]:
A = np.arange(1, 10).reshape(3, 3)
I = np.eye(3)

print(A)
print()
print(A * I)
print()
print(I * A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


#### Diagonal Matrices

A matrix that has non-diagonal elements of zero, and only the diagonal elements can be non-zero.

**Note** The diagonal matrix is not necessarily a square matrix.

A square diagonal matrix can be created by specifying an array-like object of the elements in the diagonal using the `numpy.diag()` function.

For example:

$$D = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3 \\
\end{bmatrix}$$

As can be seen, the identity matrix as described above is a special-case of the diagonal matrix.

In [21]:
diag = np.diag([1, 2, 3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


#### Triangular Matrices

Triangular matrices are those that have all zero elements either above or below the main diagonal.

They are defined as lower triangular matrices or upper triangular matrices respectively.

$$L = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 0 & 1 \\
\end{bmatrix}$$

$$U = 
\begin{bmatrix}
1 & 3 & 5 \\
0 & 1 & 4 \\
0 & 0 & 1 \\
\end{bmatrix}$$

A lower triangular matrix of a given matrix can be created by specifying the original matrix using the `numpy.tril()` function.

In [19]:
A = np.arange(1, 10).reshape(3, 3)
L = np.tril(A)

print(A)
print()
print(L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [4 5 0]
 [7 8 9]]


And an upper triangular matrix using the `numpy.triu()` function.

In [20]:
A = np.arange(1, 10).reshape(3, 3)
U = np.triu(A)

print(A)
print()
print(U)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [0 5 6]
 [0 0 9]]
