# Vector Products

There are four distinct products between two vectors, each of which have their own applications and constraints.

1. The Inner Product (Dot Product)
2. The Hadamard Product (Element-wise Product)
3. The Cross Product
4. The Outer Product

In this notebook, each of the products is implemented using Numpy arrays, first with an explicit loop-based implementation, and then using the corresponding Numpy functions.

In [1]:
import numpy as np

## Inner Product (Dot Product)

#### Definition

$$\vec{u} \cdot \vec{v} = \sum_{i = 1}^{n} u_{i}v_{i} = u_{1}v_{1} + u_{2}v_{2} + ... + u_{n}v_{n}$$

#### Signature

$$f: \mathbb{R}^{n} \times \mathbb{R}^{n} \rightarrow \mathbb{R}$$

#### Constraints

Both vectors must have the same dimensionality:

$$\vec{u}, \vec{v} \in \mathbb{R}^{n}$$

### Explicit Implementation

In [2]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

dp = 0
for i in range(len(v1)):
    dp += v1[i]*v2[i]

dp

25

### Using Numpy Functions

In [3]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

dp = np.dot(v1, v2)

dp

25

## Hadamard Product (Element-wise Product)

#### Definition

$$\vec{w} = \vec{u} \circ \vec{v}$$

where 

$$w_{i} = u_{i}v_{i}$$

#### Signature

$$f: \mathbb{R}^{n} \times \mathbb{R}^{n} \rightarrow \mathbb{R}^{n}$$

#### Constraints

Both vectors must have the same dimensionality:

$$\vec{u}, \vec{v} \in \mathbb{R}^{n}$$

#### Explicit Implementation

In [25]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

v3 = np.zeros(len(v1))
for i in range(len(v3)):
    v3[i] = v1[i]*v2[i]

v3

array([ 3., 12., 10.])

#### Using Numpy Functions

In [26]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

v3 = np.multiply(v1, v2)

print(v3)

[ 3 12 10]


## Cross Product

#### Definition

$$\vec{w} = \vec{u} \times \vec{v} = 
\begin{bmatrix}
    u_2 v_3 - u_3 v_2 \\
    u_3 v_1 - u_1 v_3 \\
    u_1 v_2 - u_2 v_1 
\end{bmatrix}$$

#### Signature

$$f : \mathbb{R}^{3} \times \mathbb{R}^{3} \rightarrow \mathbb{R}^{3}$$

#### Constraints

Both vectors must be three-dimensional.

$$u, v \in \mathbb{R}^{3}$$

#### Explicit Implementation

In [35]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

v3 = np.array([
    v1[1]*v2[2] - v1[2]*v2[1],
    v1[2]*v2[0] - v1[0]*v2[2],
    v1[0]*v2[1] - v1[1]*v2[0]
])
v3

array([-14,  13,  -5])

#### Using Numpy Functions

In [36]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2])

v3 = np.cross(v1, v2)
v3

array([-14,  13,  -5])

## Outer Product

#### Definition

$$A = \vec{u} \otimes \vec{v}$$

where 

$$A_{ij} = u_{i}v_{j}$$

#### Signature

$$f : \mathbb{R}^{m} \times \mathbb{R}^{n} \rightarrow \mathbb{R}^{m \times n}$$

#### Constraints

Each vector need not have the same dimensionality.

$$u \in \mathbb{R}^{m}, v \in \mathbb{R}^{n}$$

#### Explicit Implementation

In [28]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2, 5])

v3 = np.zeros((len(v1), len(v2)))
for i in range(len(v3)):
    for j in range(len(v3[i])):
        v3[i][j] = v1[i]*v2[j]

v3

array([[ 3.,  4.,  2.,  5.],
       [ 9., 12.,  6., 15.],
       [15., 20., 10., 25.]])

#### Using Numpy Functions

In [29]:
v1 = np.array([1, 3, 5])
v2 = np.array([3, 4, 2, 5])

v3 = np.outer(v1, v2)

v3

array([[ 3,  4,  2,  5],
       [ 9, 12,  6, 15],
       [15, 20, 10, 25]])